const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict');const fs=require('node:fs');
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});const context=await browser.newContext();const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12));const material=await crypto.subtle.importKey('raw',new TextEncoder().encode('palabra-de-prueba'),'PBKDF2',false,['deriveKey']);const key=await crypto.subtle.deriveKey({name:'PBKDF2',hash:'SHA-256',salt,iterations:600000},material,{name:'AES-GCM',length:256},false,['encrypt']);const encrypted=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,new TextEncoder().encode('cd'.repeat(24)));const b64=x=>Buffer.from(x).toString('base64');await context.route('**/access-config.json',r=>r.fulfill({json:{version:1,iterations:600000,salt:b64(salt),iv:b64(iv),ciphertext:b64(encrypted)}}));await context.route('**/firebase-config.json',r=>r.fulfill({json:{}}));const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());await page.goto('http://localhost:8080');await page.fill('#accessPassword','incorrecta');await page.click('#wordForm button');await page.waitForFunction(()=>document.querySelector('#accessError').textContent.includes('no es correcta'));assert.equal(await page.locator('#app').isVisible(),false);await page.fill('#accessPassword','palabra-de-prueba');await page.click('#wordForm button');await page.waitForFunction(()=>document.querySelector('#accessStatus').textContent.includes('Modo local'));
await page.screenshot({path:'/tmp/loma-access.png',fullPage:true});await page.selectOption('#accessFamily','camba-ceci');await page.click('#accessForm .access-submit');
assert.equal(await page.locator('#familyCount').textContent(),'7');await page.click('#addExpense');assert.equal(await page.locator('select[name=mode]').inputValue(),'equal');await page.fill('input[name=title]','Compra de prueba');await page.fill('input[name=amount]','10,01');await page.click('#selectNone');await page.click('#saveExpense');assert.match(await page.locator('#formError').textContent(),/participantes/);await page.locator('#participants input').nth(0).check();await page.locator('#participants input').nth(1).check();await page.click('#saveExpense');await page.waitForFunction(()=>!document.querySelector('#expenseDialog').open);assert.match(await page.locator('#total').textContent(),/10,01/);
await page.click('nav [data-tab=expenses]');await page.click('#expenseList [data-edit]');await page.fill('input[name=amount]','12,01');await page.click('#saveExpense');await page.selectOption('#categoryFilter','Transporte');assert.equal(await page.locator('#expenseList [data-edit]').count(),0);await page.selectOption('#categoryFilter','');assert.equal(await page.locator('#expenseList [data-edit]').count(),1);
await page.click('nav [data-tab=balances]');await page.click('[data-settle]');assert.match(await page.locator('#pending').textContent(),/0,00/);await page.click('[data-payment-delete]');assert.match(await page.locator('#pending').textContent(),/6,01/);
for(const width of [375,768,1440]){await page.setViewportSize({width,height:900});for(const tab of ['overview','expenses','balances','families','settings']){await page.click(`nav [data-tab=${tab}]`);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`Overflow ${tab} ${width}`);if(tab==='overview'||tab==='families')await page.screenshot({path:`/tmp/loma-${tab}-${width}.png`,fullPage:true});}}
await page.click('#export');const downloadEvent=page.waitForEvent('download');await page.click('#export');const download=await downloadEvent;await download.saveAs('/tmp/loma-backup.json');assert.equal(JSON.parse(fs.readFileSync('/tmp/loma-backup.json')).expenses.length,1);
await page.click('nav [data-tab=expenses]');await page.click('[data-delete]');assert.match(await page.locator('#total').textContent(),/0,00/);await page.click('nav [data-tab=settings]');await page.setInputFiles('#import','/tmp/loma-backup.json');await page.waitForFunction(()=>document.querySelector('#total').textContent.includes('12,01'));
await page.reload();await page.waitForSelector('#app:visible');assert.match(await page.locator('#total').textContent(),/12,01/);await page.click('#profile');await page.waitForSelector('#access:visible');await page.selectOption('#accessFamily','jaime-vio');await page.click('#accessForm .access-submit');await page.click('nav [data-tab=settings]');await page.click('#lock');await page.waitForSelector('#wordForm:visible');assert.equal(await page.locator('#app').isVisible(),false);assert.deepEqual(errors,[]);console.log('PASS: acceso, alta, edición, subconjunto, filtros, pagos, anulación, borrado, copia/restauración, persistencia y 15 vistas responsive; sin errores JS');await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
